import Head from 'next/head'
import styles from '../styles/Home.module.css'
import extraStyles from '../styles/Space.module.scss';

export default function Home() {
  return (
    <div style={{color : 'white'}}>
      <Head>
        <title>NSI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyStyle/>
        
      <footer>
        
      </footer>
    </div>
  )
}

function Content() {
  return (
    <div style={{marginTop: '5%'}}>
      <h1 className={styles.title}>
        <p>Welcome To Neel Space Industries</p>
      </h1>
      <p style={{textAlign: 'center'}}>
          Here is some information 
      </p>
    </div>
  )
}

function MyStyle() {
  return (
    <div className={extraStyles.stars}>
          <div className={extraStyles.twinkling}>
            <div className={extraStyles.clouds}>
              <Content/>
            </div>
          </div>  
    </div>
  ) 
}